In [ ]:
# https://mccormickml.com/2019/05/14/BERT-word-embeddings-tutorial/

In [10]:
#https://stackoverflow.com/questions/63201036/add-additional-layers-to-the-huggingface-transformers

In [1]:
!pip install transformers

     |████████████████████████████████| 2.8 MB 2.2 MB/s eta 0:00:01     |█████████████████████▉          | 1.9 MB 2.2 MB/s eta 0:00:01
  Attempting uninstall: transformers
    Found existing installation: transformers 4.12.2
    Uninstalling transformers-4.12.2:
      Successfully uninstalled transformers-4.12.2
You should consider upgrading via the '/opt/conda/bin/python -m pip install --upgrade pip' command.


In [1]:
from transformers import BertTokenizer, TFBertForSequenceClassification
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertForSequenceClassification.from_pretrained("bert-base-uncased", output_hidden_states = True)

2021-11-01 07:41:18.865863: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-01 07:41:18.879347: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-01 07:41:18.879771: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-01 07:41:18.881282: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compil

InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: out of memory

In [ ]:
from transformers import BertTokenizer, TFBertForSequenceClassification
transformer_model = TFBertForSequenceClassification.from_pretrained('bert-base-uncased', output_hidden_states=True)

In [50]:
import tensorflow as tf
input_ids = tf.keras.Input(shape=(11, ),dtype='int32')
attention_mask = tf.keras.Input(shape=(11, ), dtype='int32')

transformer = transformer_model([input_ids, attention_mask])    
hidden_states = transformer[1] # get output_hidden_states

hidden_states_size = 4 # count of the last states 
hiddes_states_ind = list(range(-hidden_states_size, 0, 1))

selected_hiddes_states = tf.keras.layers.concatenate(tuple([hidden_states[i] for i in hiddes_states_ind]))

In [70]:
model = tf.keras.models.Model(inputs = {"input_ids": input_ids, "attention_mask": attention_mask}, outputs = selected_hiddes_states)

In [76]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

In [77]:
batch_sentences = ["Hello I'm a single sentence", "And another sentence", "And the very very last one"]
encoded_input = tokenizer(batch_sentences)

In [78]:
print(encoded_input['input_ids']), print(encoded_input['attention_mask'])

[[101, 7592, 1045, 1005, 1049, 1037, 2309, 6251, 102], [101, 1998, 2178, 6251, 102], [101, 1998, 1996, 2200, 2200, 2197, 2028, 102]]
[[1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1]]


(None, None)

In [87]:
model({"input_ids" = encoded_input})

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (3514426950.py, line 1)

In [2]:
batch_sentences = ["Hello I'm a single sentence", "And another sentence", "And the very very last one"]

In [3]:
encoded_inputs = tokenizer(batch_sentences)

In [4]:
batch = tokenizer(batch_sentences, padding=True, truncation=True, return_tensors="tf")

2021-11-01 07:42:37.737253: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-01 07:42:37.739841: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-01 07:42:37.740351: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero


ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.

In [31]:
batch.values

<bound method BatchEncoding.values of {'input_ids': <tf.Tensor: shape=(3, 9), dtype=int32, numpy=
array([[ 101, 8667,  146,  112,  182,  170, 1423, 5650,  102],
       [ 101, 1262, 1330, 5650,  102,    0,    0,    0,    0],
       [ 101, 1262, 1103, 1304, 1304, 1314, 1141,  102,    0]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(3, 9), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(3, 9), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 0]], dtype=int32)>}>

In [69]:
model.predict(batch)

ValueError: Unsupported value type BatchEncoding returned by IteratorSpec._serialize

In [29]:
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='pt') 
output = model(**encoded_input)

In [32]:
output.shape

AttributeError: 'BaseModelOutputWithPoolingAndCrossAttentions' object has no attribute 'shape'

In [34]:
hidden_states  = output[2]

In [36]:
hidden_states

(tensor([[[ 0.1686, -0.2858, -0.3261,  ..., -0.0276,  0.0383,  0.1640],
          [-0.2368,  0.3720,  0.9008,  ...,  0.0719,  1.2566,  0.4192],
          [ 0.0120,  0.3938, -0.8486,  ...,  0.6180,  0.9804,  0.1418],
          ...,
          [ 0.4818,  0.6824,  0.2637,  ...,  0.4731,  0.7393,  0.3412],
          [-0.3585,  0.2777, -0.1210,  ...,  0.5949,  0.6856,  0.7453],
          [-0.4771,  0.0871, -0.0770,  ..., -0.2191,  0.3020,  0.0196]]],
        grad_fn=<NativeLayerNormBackward>),
 tensor([[[-0.0221,  0.0724, -0.2123,  ...,  0.2558, -0.0699, -0.0578],
          [-0.1039,  0.6296,  1.3882,  ...,  0.2655,  1.8529,  0.3532],
          [ 0.2680,  0.8338, -0.6742,  ...,  0.1437,  1.3582,  0.5122],
          ...,
          [ 0.9177,  0.9559,  0.1002,  ..., -0.1845,  0.6330,  0.1174],
          [-0.1476,  0.0967, -0.2037,  ...,  0.2801,  0.3652,  0.4488],
          [-0.3806,  0.0126, -0.1525,  ..., -0.1905,  0.3529,  0.1331]]],
        grad_fn=<NativeLayerNormBackward>),
 tensor([[[-0.

In [38]:
import torch
token_embeddings = torch.stack(hidden_states, dim=0)

In [39]:
token_embeddings.size()

torch.Size([13, 1, 12, 768])

In [40]:
token_embeddings = torch.squeeze(token_embeddings, dim=1)

token_embeddings.size()

torch.Size([13, 12, 768])

In [41]:
token_embeddings = token_embeddings.permute(1,0,2)

token_embeddings.size()

torch.Size([12, 13, 768])

In [42]:
# Stores the token vectors, with shape [22 x 768]
token_vecs_sum = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:

    # `token` is a [12 x 768] tensor

    # Sum the vectors from the last four layers.
    sum_vec = torch.sum(token[-4:], dim=0)
    
    # Use `sum_vec` to represent `token`.
    token_vecs_sum.append(sum_vec)

print ('Shape is: %d x %d' % (len(token_vecs_sum), len(token_vecs_sum[0])))


Shape is: 12 x 768


In [43]:
# `hidden_states` has shape [13 x 1 x 22 x 768]

# `token_vecs` is a tensor with shape [22 x 768]
token_vecs = hidden_states[-2][0]

# Calculate the average of all 22 token vectors.
sentence_embedding = torch.mean(token_vecs, dim=0)

In [44]:
# Stores the token vectors, with shape [22 x 3,072]
token_vecs_cat = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:
    
    # `token` is a [12 x 768] tensor

    # Concatenate the vectors (that is, append them together) from the last 
    # four layers.
    # Each layer vector is 768 values, so `cat_vec` is length 3,072.
    cat_vec = torch.cat((token[-1], token[-2], token[-3], token[-4]), dim=0)
    
    # Use `cat_vec` to represent `token`.
    token_vecs_cat.append(cat_vec)

print ('Shape is: %d x %d' % (len(token_vecs_cat), len(token_vecs_cat[0])))

Shape is: 12 x 3072
